import { NextResponse } from "next/server";
import crypto from "crypto";
import path from "path";
import fs from "fs";
import { cookies } from "next/headers";
import { verifySessionToken } from "@/lib/auth/security";
import { findUserById } from "@/lib/auth/db";
import { checkRateLimit } from "@/lib/auth/rate-limit";
import { handleServerError } from "@/lib/auth/error-handler";

const MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024; // Hard 5MB limit
const MAX_MULTIPART_BODY_BYTES = MAX_FILE_SIZE_BYTES + 64 * 1024;
const ALLOWED_MIME_TYPES = new Map<string, string>([
  ["image/jpeg", ".jpg"],
  ["image/png", ".png"],
  ["image/webp", ".webp"],
  ["application/pdf", ".pdf"],
]);

function verifyMagicBytes(buffer: Buffer): string | null {
  if (buffer.length < 12) return null;
  if (buffer.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff]))) return "image/jpeg";
  if (buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (buffer.subarray(0, 4).toString("ascii") === "RIFF" && buffer.subarray(8, 12).toString("ascii") === "WEBP") return "image/webp";
  if (buffer.subarray(0, 5).toString("ascii") === "%PDF-") return "application/pdf";
  return null;
}

function containsActivePdfContent(buffer: Buffer): boolean {
  // This is a defense-in-depth check, not a substitute for malware scanning.
  // Reject common PDF actions that can execute code or launch embedded content.
  return ["/JavaScript", "/JS", "/OpenAction", "/AA", "/Launch", "/EmbeddedFile", "/RichMedia"].some((marker) =>
    buffer.includes(Buffer.from(marker, "ascii"))
  );
}

import os from "os";

const getStorageDir = () => {
  if (process.env.VERCEL || process.env.NODE_ENV === "production") {
    return path.join(os.tmpdir(), "nirmaan_uploads");
  }
  return path.join(process.cwd(), "storage", "uploads");
};

const STORAGE_DIR = getStorageDir();

function ensureStorageDir(directory: string): void {
  if (!fs.existsSync(directory)) {
    fs.mkdirSync(directory, { recursive: true });
  }
}

export async function POST(req: Request) {
  try {
    const contentLength = Number(req.headers.get("content-length"));
    if (Number.isFinite(contentLength) && contentLength > MAX_MULTIPART_BODY_BYTES) {
      return NextResponse.json({ error: "Upload request exceeds the maximum allowed size." }, { status: 413 });
    }

    const clientIp = req.headers.get("x-forwarded-for") || "unknown";

    const rateLimit = checkRateLimit(`upload:${clientIp}`, 10, 60 * 60 * 1000);
    if (!rateLimit.success) {
      return NextResponse.json(
        { error: "Upload rate limit exceeded. Please try again later." },
        { status: 429, headers: { "Retry-After": String(rateLimit.retryAfterSeconds) } }
      );
    }

    const cookieStore = await cookies();
    const sessionToken = cookieStore.get("session_token")?.value;
    const payload = sessionToken ? verifySessionToken(sessionToken) : null;

    if (!payload) {
      return NextResponse.json({ error: "Authentication required to upload files." }, { status: 401 });
    }

    const user = findUserById(payload.userId);
    if (!user) {
      return NextResponse.json({ error: "Invalid user session." }, { status: 401 });
    }

    const formData = await req.formData();
    const file = formData.get("file");

    if (!(file instanceof File)) {
      return NextResponse.json({ error: "No file provided." }, { status: 400 });
    }

    if (file.size <= 0 || file.size > MAX_FILE_SIZE_BYTES) {
      return NextResponse.json({ error: "File size exceeds 5MB limit." }, { status: 400 });
    }

    const allowedExtension = ALLOWED_MIME_TYPES.get(file.type);
    if (!allowedExtension) {
      return NextResponse.json({ error: "Invalid file type. Only JPEG, PNG, WebP, and PDF are permitted." }, { status: 400 });
    }

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    const detectedMime = verifyMagicBytes(buffer);
    if (!detectedMime || detectedMime !== file.type) {
      return NextResponse.json({ error: "Security warning: File content signature mismatch detected." }, { status: 400 });
    }

    if (detectedMime === "application/pdf" && containsActivePdfContent(buffer)) {
      return NextResponse.json({ error: "PDF contains active content and cannot be uploaded." }, { status: 400 });
    }

    const safeUUID = crypto.randomBytes(16).toString("hex");
    const safeFilename = `${safeUUID}${allowedExtension}`;

    // Store uploads in an authenticated user's own server-side directory.
    // `user.id` is generated by the server and never supplied by the request.
    const storageRoot = path.resolve(STORAGE_DIR);
    const userStorageDir = path.resolve(storageRoot, user.id);
    if (!userStorageDir.startsWith(`${storageRoot}${path.sep}`)) {
      return NextResponse.json({ error: "Invalid upload storage path." }, { status: 400 });
    }
    ensureStorageDir(userStorageDir);
    const safePath = path.resolve(/*turbopackIgnore: true*/ userStorageDir, safeFilename);
    if (!safePath.startsWith(`${userStorageDir}${path.sep}`)) {
      return NextResponse.json({ error: "Invalid upload filename." }, { status: 400 });
    }

    fs.writeFileSync(safePath, buffer, { flag: "wx", mode: 0o600 });

    return NextResponse.json({
      success: true,
      message: "File uploaded successfully.",
      fileId: safeUUID,
    });
  } catch (error) {
    return handleServerError(error, "File Upload Error");
  }
}
